language: python
python:
    - 3.6
services:
    - postgresql
install:
    - pip install -r requirements.txt flake8 python-coveralls safety psycopg2
env:
    - SECRET_KEY='pipo' EMAIL_HOST_PASSWORD='pipo' POSTGRES_HOST='localhost' POSTGRES_PASSWORD=''
script:
    - ./manage.py migrate
    - coverage run manage.py test
    - flake8 .
    - safety check
after_success:
    - coveralls
