language: python
sudo: required
python:
    - 3.6
services:
    - postgresql
    - docker
install:
    - pip install -r requirements.txt flake8 python-coveralls safety psycopg2 raven
env:
    - SECRET_KEY='pipo' EMAIL_HOST_PASSWORD='pipo' POSTGRES_HOST='localhost' POSTGRES_PASSWORD='' RAVEN=True DSN=''
script:
    - ./manage.py migrate
    - coverage run manage.py test
    - flake8 .
    - safety check
    - docker build -t $TRAVIS_REPO_SLUG .
after_success:
    - coveralls
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push $TRAVIS_REPO_SLUG
