version: '3'

volumes:
  srv:

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
  memcached:
    image: memcached:alpine
    restart: unless-stopped
  app:
    build: .
    restart: unless-stopped
    volumes:
      - "srv:/srv"
    env_file:
      - .env
    depends_on:
      - postgres
      - memcached
  nginx:
    image: nim65s/ndh:nginx
    restart: unless-stopped
    volumes:
      - "srv:/srv"
    ports:
      - "6500:8000"
    depends_on:
      - app
