version: '3'

volumes:
  srv:

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
  memcached:
    image: memcached:alpine
    restart: unless-stopped
  app:
    image: nim65s/frigo
    build: .
    restart: unless-stopped
    volumes:
      - "srv:/srv"
    env_file:
      - .env
  nginx:
    image: nim65s/ndh:nginx
    restart: unless-stopped
    volumes:
      - "srv:/srv"
    labels:
      - "traefik.frontend.rule=Host:frigo.totheweb.fr"
    networks:
      - web
      - default

networks:
  web:
    external: true
