version: '2'

services:
  traefik:
    image: traefik:1.5-alpine
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

networks:
  web:
    external: true
