# Generated by Django 2.0.2 on 2018-02-24 10:18

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import frigo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField(auto_now_add=True, verbose_name='début')),
            ],
            options={
                'ordering': ('debut',),
            },
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='repas',
            name='mangeurs',
            field=models.ManyToManyField(to='frigo.Utilisateur'),
        ),
        migrations.AddField(
            model_name='repas',
            name='periode',
            field=models.ForeignKey(default=frigo.models.last_periode, on_delete=django.db.models.deletion.PROTECT, to='frigo.Periode'),
        ),
        migrations.AddField(
            model_name='course',
            name='payeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frigo.Utilisateur'),
        ),
        migrations.AddField(
            model_name='course',
            name='periode',
            field=models.ForeignKey(default=frigo.models.last_periode, on_delete=django.db.models.deletion.PROTECT, to='frigo.Periode'),
        ),
    ]
